### ISSUE TITLE
RTL - c-lightning - Orbot - F-Droid

### ISSUE THREAD

**Issue by PsySc0rpi0n** [seth586/guides#10]
Hello.

After trying to figure out my issue in RTL Telegram channel, I was suggested to reach out for you here.
I'm using RTL and c-lightning and I was trying to setup Orbot/Tor on my phone to access my node via onion address.
But instructions here:
```https://github.com/Ride-The-Lightning/RTL/blob/master/docs/RTL_TOR_setup.md```

says:
`Download Orbot for android (add their repos to F-Droid here: https://guardianproject.info/fdroid/`

I don't know what to do with the F-Droid part. How do we install _**their repositories for F-Droid**_. When I go to the suggested site I can only see a bunch of links and QR codes. But what to do with them? There are no instructions on what to do with F-Droid.

Could you please clarify?
Thanks
Psy

**Comment by saubyk** [comment]
Hey @seth586 I told you someday someone will come with questions on the document you created for RTL! 

Today is that day! 😄

**Comment by seth586** [comment]
Option 1:
Once you install F-Droid, install a qr code scanner. I personally like [Binary Eye](https://f-droid.org/en/packages/de.markusfisch.android.binaryeye/). Scan the code, and open the link with F-Droid.

Option 2:
Alternatively, you can open F-Droid, click settings ⚙ , click "Repositories", click the Add Button ➕, and type in the URL given on the guardianproject website: `https://guardianproject.info/fdroid/repo`

**Comment by PsySc0rpi0n** [comment]
> Option 1:
> Once you install F-Droid, install a qr code scanner. I personally like [Binary Eye](https://f-droid.org/en/packages/de.markusfisch.android.binaryeye/). Scan the code, and open the link with F-Droid.
> 
> Option 2:
> Alternatively, you can open F-Droid, click settings gear , click "Repositories", click the Add Button heavy_plus_sign, and type in the URL given on the guardianproject website: `https://guardianproject.info/fdroid/repo`

There is no F-Droid app in Google Play, but I downloaded it from their site.
Now, what QR codes should I scan and what will they do?


Edited;
Ok, after installing F-Droid, GuardianProject repository is already there. I activated it.
Now what? What is this for?
