### ISSUE TITLE
Update TrueNASnode scripts

### ISSUE THREAD

**Issue by ricko1** [seth586/guides#14]
I just setup a TrueNASnode with the latest versions
It's a great guide. However there are a few issues that need updates:

1. loopd won't start using command loopd --lnd.macaroondir=/var/db/lnd/data/chain/bitcoin/mainnet --lnd.tlspath=/var/db/lnd/tls.cert --server.proxy=localhost:9050

Error only use --lnd.macaroonpath

Solution Replace the command and  startup script containing: 
loopd --lnd.macaroondir=/var/db/lnd/data/chain/bitcoin/mainnet
with
loopd --lnd.macaroonpath=/var/db/lnd/data/chain/bitcoin/mainnet/admin.macaroon

2. Mempool service nginx won't start due to nginx-mempool.conf missing a ) and { on 2 locations from line 17 to 26, error at line 19

Solution replace code with below code (two changes, added ") {" after the two "|>")

        # used to rewrite resources from /<lang>/ to /en-US/
        location ~ ^/(ar|bg|bs|ca|cs|da|de|et|el|es|eo|eu|fa|fr|gl|ko|hr|id|it|he|ka|lv|lt|hu|mk|ms|nl|ja|ka|no|nb|nn|pl|pt|pt-BR|ro|ru|sk|sl|sr|sh|fi|sv|th|tr|uk|>) {
                add_header Vary Cookie;
                rewrite ^/[a-zA-Z-]*/resources/(.*) /en-US/resources/$1;
        }
        # used for cookie override
        location ~ ^/(ar|bg|bs|ca|cs|da|de|et|el|es|eo|eu|fa|fr|gl|ko|hr|id|it|he|ka|lv|lt|hu|mk|ms|nl|ja|ka|no|nb|nn|pl|pt|pt-BR|ro|ru|sk|sl|sr|sh|fi|sv|th|tr|uk|>) {
                add_header Vary Cookie;
                try_files $uri $uri/ /$1/index.html =404;
        }

I also have a few suggestions for improvements
A. add tmux command when opening terminal sessions
The first start of electrum sync takes hours and closing the terminal stops the process since it runs in the foreground. Your PC must keep running with no network interruptions otherwise.

B. if you already have a copy of the blockchain (like me) you can copy the "blocks" and "chainstate" folders to "/mnt/tank/iocage/jails/bitcoin/root/var/db/bitcoin" (replace "tank" with Zpool name) with (Win)SCP. That 380GB (19-7-2021) copy only takes a few hours (LAN gbit speed) instead of days (WAN xx mbit speed).

Thank you for the great guide.

**Comment by ricko1** [comment]
Added my first two pull requests. I'm not a programmer but can read error messages and fix simple problems with google, trail and error. Please verify my work. 

https://github.com/seth586/guides/pull/15
https://github.com/seth586/guides/pull/16

Even with this the experience was better then trying to get Armory 0.96.5 to work and keep working on my desktop (hence the full blockchain) and it can run on my NAS :) Thank you again, it works great.

Edit: spoke too soon, RTL loop https and missing path issue. simple fix
https://github.com/seth586/guides/pull/17

**Comment by seth586** [comment]
Thank you for finding these, fixes merged!
