### ISSUE TITLE
Stuck at "Create RPC credentials for Bitcoin Core"

### ISSUE THREAD

**Issue by Silarous** [seth586/guides#19]
Guide has gone smooth up to this point on my Truenas box.  After entering this command:

python3 ./rpcauth.py electrs

I get an error "python3: Command not found."

I wiped the Jail and started over two times and keep getting the same issue.  What am I missing?

<img width="835" alt="Screen Shot 2021-09-27 at 5 45 48 PM" src="https://user-images.githubusercontent.com/56011055/134995546-bacb5d81-db8b-489a-9416-f8bf1ec07b62.png">

**Comment by Jacquesvw** [comment]
Install Python 3.8:
`# pkg install -y python38`

Run rpcauth.py:
`# python3.8 ./rpcauth.py electrs`
