### ISSUE TITLE
OpenSSL error installing dependencies for RTL on Truenas 12.0-U6

### ISSUE THREAD

**Issue by joshr4** [seth586/guides#21]
After following this awesome and extremely thorough guide, I've got everything up and running on my TrueNAS server, except for RTL.

When trying to run `npm install`, I'm met with an OpensSLL error:
`ld-elf.so.1: /lib/libcrypto.so.111: version OPENSSL_1_1_1e required by /usr/local/bin/node not found`

I was able to find some info on why this is not available:
https://www.freebsd.org/security/advisories/FreeBSD-EN-21:24.libcrypto.asc
https://security.truenas.com/errata/2021-08-24-freebsd-en-21-24-libcrypto/

I'm hoping that upgrading my server from TrueNAS-12.0-U6 to TrueNAS-12.0-U8 may fix the issue. Figured I'd document it here in case that does the trick.

**Comment by seth586** [comment]
At TrueNAS' root, run `iocage list` to determine the FreeBSD version of your bitcoin jail as well. Jails are not automatically updated to the most recent patch and release level as the base operating system.

To make a version upgrade (such as 12.2-RELEASE to 12.3-RELEASE) run `iocage upgrade bitcoin -r 12.3-RELEASE` at TrueNAS root. 

To make a patch level upgrade (such as 12.2-RELEASE to 12.2-RELEASE-p15) run `iocage update bitcoin` . 

These process can take a while, so you might want to consider using `tmux` so the process doesnt abort if your SSH session ends. You may get an (end) reading in the console to look over the list of changes, press Q to scroll thru the data.

My bitcoin jail version 12.3-RELEASE-p5 command `pkg search openssl` shows the latest version as `1.1.1n`.
