### ISSUE TITLE
unable to find rpcuser in config, cannot start w/o RPC connectionError

### ISSUE THREAD

**Issue by omid-1985** [seth586/guides#23]
On the lnd page and on the [LND Startup and initialization](https://github.com/seth586/guides/blob/master/FreeNAS/bitcoin/freenas_5_lnd.md#lnd-startup-and-initialization) section, the result of running lnd package under lnd user is:
`su -m lnd -c 'lnd --configfile=/usr/local/etc/lnd.conf'`

![Screenshot from 2022-11-29 15-33-28](https://user-images.githubusercontent.com/19699810/204440568-d3038d7a-7e54-400b-ac54-320af2597cac.png)

But running it under root is fine:
`lnd --configfile=/usr/local/etc/lnd.conf`

![Screenshot from 2022-11-29 15-36-10](https://user-images.githubusercontent.com/19699810/204440010-2956c423-fb7e-4082-b563-631d4700b610.png)

following this instruction stops you here as lnd user does not have permission to read from /var/db/bitcoin.
![Screenshot from 2022-11-29 15-49-03](https://user-images.githubusercontent.com/19699810/204441588-457fde7d-ad3f-4fc3-9fec-1e4c7ebc260c.png)

**Comment by omid-1985** [comment]
Reading more about it, [lnd Github repo](https://github.com/lightningnetwork/lnd/blob/master/docs/INSTALL.md#using-bitcoind-or-litecoind) explicitly mentions that:
"The auth parameters rpcuser and rpcpass parameters can typically be determined by lnd for a bitcoind instance **running under the same user**."

We have lnd running under lnd user and running bitcoind under bitcoin user. Thus we need to pass the auth parameters in lnd.conf by adding these parameters into /usr/local/etc/lnd.conf:
`bitcoind.rpcuser=***youruser***`
`bitcoind.rpcpass=***yourpass***`
`bitcoind.zmqpubrawblock=tcp://127.0.0.1:28332`
`bitcoind.zmqpubrawtx=tcp://127.0.0.1:28333`

The above help to go as far as lnd wallet creation, but after that lnd process fails due to another permission issue:
![Screenshot 2022-12-09 180607](https://user-images.githubusercontent.com/19699810/206645428-be20b6a1-e748-4c85-a7ab-44ce3925d306.png)

**Comment by marcoacheron** [comment]
@omid-1985 In order to get past the cookie error, I had to add lnd to the _tor group.

`pw usermod lnd -G lnd,_tor`

**Comment by seth586** [comment]
Yeah for the cookie authentication the lnd user needs to be added to the tor and bitcoin groups `pw usermod lnd -G lnd,_tor,bitcoin`

Fixed!
