### ISSUE TITLE
RTL not working.

### ISSUE THREAD

**Issue by kklara** [seth586/guides#3]
Following the guides I have problem with RTL.

LND seems to be working just fine. I have connections to several peers, I have tor address, I am synced with bitcoin mainnet. I tried to install nginx to test that tor is working and it is. So the problem seems to be with RTL and nodejs. The only difference from the guides is that I have bitcoind in separate machine in local network but that should not affect it.

This is when I try to start RTL manually:
```
root@lnd:~ # node rtl
internal/modules/cjs/loader.js:657
    throw err;
    ^

Error: Cannot find module '/root/rtl'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:655:15)
    at Function.Module._load (internal/modules/cjs/loader.js:580:25)
    at Function.Module.runMain (internal/modules/cjs/loader.js:868:12)
    at internal/main/run_main_module.js:21:11
```

service rtl start/stop/restart are not reporting any errors, the service can be started. However RTL is not reachable on IP:3000 neither over tor address. neither on localhost:3000

* version of `lnd` 0.6.1-beta commit=v0.6.1-beta-rc2
* operating system FreeBSD 11.2-STABLE
* version of  bitcoind 0.18

As this is all very new to me, I would appreciate any help.
Perhaps it may be something with user permissions?

**Comment by kklara** [comment]
So the problem is that after executing the first few commands from https://github.com/seth586/guides/blob/master/FreeNAS/freenas_6_rtl.md

it creates this directory structure:

```
 ~ <-- actually /root
     /rtl <-- no files here, only package.lock after npm install
           /RTL-0.3.0  <-- all files are here
```

After I moved content of  /root/rtl/RTL-0.3.0 to the parent directory /root/rtl and executed npm install there it started working.

**Comment by seth586** [comment]
Thanks for pointing this out. I changed the RTL guide to address this issue.

The problem was that after creating the `~/rtl` folder, moving the `~/RTL-release` folder to `~/rtl` moved to a subdirectory, and did not rename the folder.

The solution was to remove the folder creation process and use the `mv` command to rename `~/RTL-release` folder to `~/rtl`.
