### ISSUE TITLE
CookieAuthFileGroupReadable is set, but will have no effect

### ISSUE THREAD

**Issue by ravinggenius** [seth586/guides#7]
I'm following the tutorial for setting up Tor. After starting the Tor service (`service tor start`), I saw the following warning:

```
[warn] CookieAuthFileGroupReadable is set, but will have no effect: you must specify an explicit CookieAuthFile to have it group-readable.
```

I'm setting mine to `/var/lib/tor/control_auth_cookie`, as suggested at https://tor.stackexchange.com/a/8705. If this is a bad idea or another location is more appropriate, please let me know (anyone).

**Comment by seth586** [comment]
The default cookie path (when unspecified) is '/var/db/tor/control_auth_cookie'

The warning message was a nuisance, as the default cookie was still given group read permissions.

Adding the following line to `/usr/local/etc/tor/torrc` will remove the warning:

```
CookieAuthFile /var/db/tor/control_auth_cookie
```
I'll add it to the guide. Thanks!
