### ISSUE TITLE
mysql fails to start due to incorrect permissions on /var/run/mysql

### ISSUE THREAD

**Issue by tabbek** [seth586/guides#8]
Ran into an issue installing mempool getting mysql-server to start.
Found that the issue was due to /var/run/mysql directory being owned by root with 755 permissions.
chowned /var/run/mysql to mysql:mysql and it started correctly.

**Comment by seth586** [comment]
yeah thats been a growing pain of standardization , `/var/run` is the placeholder for PIDs, but sql has kept their PIDs in /tmp for the longest time until a recent change.

using pkg is supposed to do this automatically.

I'll add it to the guide.
