### ISSUE TITLE
Starting Lightning Lab's LND

### ISSUE THREAD

**Issue by fenngineering** [seth586/guides#9]
I have managed to follow this guide up to Install Lightning Lab's LND.

I have successfully created the wallet etc, but I am receiving the below error when  running loopd:-

`root@bitcoin-node:~ # loopd --lnd.macaroondir=/var/db/lnd/data/chain/bitcoin/mainnet --lnd.tlspath=/var/db/lnd/tls.cert --server.proxy=localhost:9050
2021-01-20 04:18:36.462 [INF] LOOPD: Version: 0.9.0-beta commit=
2021-01-20 04:18:36.463 [INF] LNDC: Creating lnd connection to localhost:10009
2021-01-20 04:18:36.474 [INF] LNDC: Connected to lnd
loopd exited with an error: lnd compatibility check failed: unable to get info for lnd node: rpc error: code = Unimplemented desc = unknown service lnrpc.Lightning`

Please can you help?
Thanks

**Comment by seth586** [comment]
looks like you installed an old version (0.9.0) current release is (11.4), make sure to follow the link to find the latest release
